/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ComputerControl;
import exception.InputKosongException;
import javax.swing.JOptionPane;
import model.Computer;
import exception.InputIDException;
import exception.InputJenisException;



/**
 *
 * Benidiktus Valerino Gozen - 200710606
 */
public class ComputerView extends javax.swing.JFrame {
    private ComputerControl computerControl;
    String action = null;
    private boolean value;
    
    

    /**
     * Creates new form DosenView
     */
    public ComputerView() {
       
        
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);    
        computerControl = new ComputerControl();
        showComputer();
        
    }
    
    public void setComponent(boolean value){
        idInput.setEnabled(false);
        namaInput.setEnabled(value);
        processorInput.setEnabled(value);
        kapasitasRAMInput.setEnabled(value);
        dayaListrikInput.setEnabled(false);
        bateraiInput.setEnabled(false);
        jRadioDesktop.setEnabled(value);
        jRadioLaptop.setEnabled(value);
        
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
        
    }
    
    
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        idInput.setText("");
        namaInput.setText("");
        processorInput.setText("");
        kapasitasRAMInput.setText("");
        inputSearch.setText("");
        dayaListrikInput.setText("");
        bateraiInput.setText("");
    }
    
    public void showComputer(){
        txtLaptop.setText(computerControl.showDataLaptop());
        txtDesktop.setText(computerControl.showDataComputer());
    }
    
    public void inputKosongException() throws InputKosongException{
        if (idInput.getText().isEmpty() || namaInput.getText().isEmpty()
                || processorInput.getText().isEmpty() 
                || kapasitasRAMInput.getText().isEmpty()) {
            throw  new InputKosongException();
        }
    }
    
    public void inputIDException() throws InputIDException{
        if (idInput.getText().length() < 5 || 
                idInput.getText().length() > 8) {
            throw new InputIDException();
        }
    }
    
    public void inputJenisException() throws InputJenisException{
        if (!jRadioLaptop.isSelected()  && !jRadioDesktop.isSelected() ) {
            throw  new InputJenisException();
            
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize
     * the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sidebarPanel = new javax.swing.JPanel();
        lecturerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuTransaksiBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        titleContent = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        containerInputID = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        containerInputNama = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        containerInputJenis = new javax.swing.JPanel();
        jenisLabel = new javax.swing.JLabel();
        processorInput = new javax.swing.JTextField();
        containerInputKapasitasRAM = new javax.swing.JPanel();
        kapasitasRAMLabel = new javax.swing.JLabel();
        kapasitasRAMInput = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        showDataPanelSeri = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLaptop = new javax.swing.JTextArea();
        showDataPanelMovie = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDesktop = new javax.swing.JTextArea();
        containerInputDaya = new javax.swing.JPanel();
        nidLabel1 = new javax.swing.JLabel();
        dayaListrikInput = new javax.swing.JTextField();
        containerInputKapasitasBaterai = new javax.swing.JPanel();
        nidLabel2 = new javax.swing.JLabel();
        bateraiInput = new javax.swing.JTextField();
        jRadioDesktop = new javax.swing.JRadioButton();
        jRadioLaptop = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        sidebarPanel.setBackground(new java.awt.Color(153, 153, 255));

        lecturerPanel.setBackground(new java.awt.Color(255, 102, 204));
        lecturerPanel.setToolTipText("");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("200710606");

        javax.swing.GroupLayout lecturerPanelLayout = new javax.swing.GroupLayout(lecturerPanel);
        lecturerPanel.setLayout(lecturerPanelLayout);
        lecturerPanelLayout.setHorizontalGroup(
            lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturerPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        lecturerPanelLayout.setVerticalGroup(
            lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lecturerPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );

        menuTransaksiBtn.setText("Menu Transaksi");
        menuTransaksiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTransaksiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuTransaksiBtn)
                    .addComponent(lecturerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(lecturerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(menuTransaksiBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));
        containerPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        containerPanel.setPreferredSize(new java.awt.Dimension(724, 660));

        titleContent.setForeground(new java.awt.Color(0, 0, 0));
        titleContent.setText("COMPUTER");

        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        containerInputID.setPreferredSize(new java.awt.Dimension(300, 65));

        idLabel.setText("ID Computer");

        javax.swing.GroupLayout containerInputIDLayout = new javax.swing.GroupLayout(containerInputID);
        containerInputID.setLayout(containerInputIDLayout);
        containerInputIDLayout.setHorizontalGroup(
            containerInputIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        containerInputIDLayout.setVerticalGroup(
            containerInputIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        containerInputNama.setPreferredSize(new java.awt.Dimension(300, 65));

        namaLabel.setText("Nama Model");

        javax.swing.GroupLayout containerInputNamaLayout = new javax.swing.GroupLayout(containerInputNama);
        containerInputNama.setLayout(containerInputNamaLayout);
        containerInputNamaLayout.setHorizontalGroup(
            containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel)
                    .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        containerInputNamaLayout.setVerticalGroup(
            containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        containerInputJenis.setPreferredSize(new java.awt.Dimension(300, 65));

        jenisLabel.setText("Jenis Processor");

        javax.swing.GroupLayout containerInputJenisLayout = new javax.swing.GroupLayout(containerInputJenis);
        containerInputJenis.setLayout(containerInputJenisLayout);
        containerInputJenisLayout.setHorizontalGroup(
            containerInputJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputJenisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenisLabel)
                    .addComponent(processorInput, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        containerInputJenisLayout.setVerticalGroup(
            containerInputJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputJenisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        containerInputKapasitasRAM.setPreferredSize(new java.awt.Dimension(300, 65));

        kapasitasRAMLabel.setText("Kapasitas RAM");

        javax.swing.GroupLayout containerInputKapasitasRAMLayout = new javax.swing.GroupLayout(containerInputKapasitasRAM);
        containerInputKapasitasRAM.setLayout(containerInputKapasitasRAMLayout);
        containerInputKapasitasRAMLayout.setHorizontalGroup(
            containerInputKapasitasRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputKapasitasRAMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputKapasitasRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kapasitasRAMLabel)
                    .addComponent(kapasitasRAMInput, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        containerInputKapasitasRAMLayout.setVerticalGroup(
            containerInputKapasitasRAMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputKapasitasRAMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kapasitasRAMLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kapasitasRAMInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        txtLaptop.setEditable(false);
        txtLaptop.setColumns(20);
        txtLaptop.setRows(5);
        jScrollPane1.setViewportView(txtLaptop);

        javax.swing.GroupLayout showDataPanelSeriLayout = new javax.swing.GroupLayout(showDataPanelSeri);
        showDataPanelSeri.setLayout(showDataPanelSeriLayout);
        showDataPanelSeriLayout.setHorizontalGroup(
            showDataPanelSeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDataPanelSeriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );
        showDataPanelSeriLayout.setVerticalGroup(
            showDataPanelSeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDataPanelSeriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtDesktop.setEditable(false);
        txtDesktop.setColumns(20);
        txtDesktop.setRows(5);
        jScrollPane3.setViewportView(txtDesktop);

        javax.swing.GroupLayout showDataPanelMovieLayout = new javax.swing.GroupLayout(showDataPanelMovie);
        showDataPanelMovie.setLayout(showDataPanelMovieLayout);
        showDataPanelMovieLayout.setHorizontalGroup(
            showDataPanelMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDataPanelMovieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );
        showDataPanelMovieLayout.setVerticalGroup(
            showDataPanelMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDataPanelMovieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        containerInputDaya.setPreferredSize(new java.awt.Dimension(300, 65));

        nidLabel1.setText("Daya Listrik");

        javax.swing.GroupLayout containerInputDayaLayout = new javax.swing.GroupLayout(containerInputDaya);
        containerInputDaya.setLayout(containerInputDayaLayout);
        containerInputDayaLayout.setHorizontalGroup(
            containerInputDayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputDayaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputDayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nidLabel1)
                    .addComponent(dayaListrikInput, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        containerInputDayaLayout.setVerticalGroup(
            containerInputDayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputDayaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nidLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayaListrikInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        containerInputKapasitasBaterai.setPreferredSize(new java.awt.Dimension(300, 65));

        nidLabel2.setText("Baterai");

        javax.swing.GroupLayout containerInputKapasitasBateraiLayout = new javax.swing.GroupLayout(containerInputKapasitasBaterai);
        containerInputKapasitasBaterai.setLayout(containerInputKapasitasBateraiLayout);
        containerInputKapasitasBateraiLayout.setHorizontalGroup(
            containerInputKapasitasBateraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputKapasitasBateraiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerInputKapasitasBateraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nidLabel2)
                    .addComponent(bateraiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        containerInputKapasitasBateraiLayout.setVerticalGroup(
            containerInputKapasitasBateraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerInputKapasitasBateraiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nidLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bateraiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        buttonGroup1.add(jRadioDesktop);
        jRadioDesktop.setForeground(new java.awt.Color(0, 0, 0));
        jRadioDesktop.setText("Desktop");
        jRadioDesktop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDesktopActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioLaptop);
        jRadioLaptop.setForeground(new java.awt.Color(0, 0, 0));
        jRadioLaptop.setText("Laptop");
        jRadioLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLaptopActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Desktop");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Laptop");

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerPanelLayout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                                    .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(containerInputNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(containerInputKapasitasRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(containerInputJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(containerInputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioDesktop)
                                        .addComponent(containerInputKapasitasBaterai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(containerInputDaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showDataPanelSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRadioLaptop)
                                        .addComponent(jLabel3))
                                    .addGap(26, 26, 26))
                                .addGroup(containerPanelLayout.createSequentialGroup()
                                    .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addBtn)
                                        .addComponent(titleContent))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deleteBtn)
                                    .addGap(133, 133, 133)
                                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchBtn))))
                        .addGroup(containerPanelLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelBtn)))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(containerPanelLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(showDataPanelMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(411, Short.MAX_VALUE)))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleContent)
                .addGap(18, 18, 18)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(editBtn)
                            .addComponent(deleteBtn)
                            .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(containerInputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRadioDesktop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(containerInputDaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(containerInputJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(containerInputKapasitasRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jRadioLaptop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerInputKapasitasBaterai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addGap(10, 10, 10)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addComponent(showDataPanelSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
                    .addContainerGap(444, Short.MAX_VALUE)
                    .addComponent(showDataPanelMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)))
        );

        jScrollPane2.setViewportView(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        idInput.setEnabled(false);
        action = "Ubah";
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        clearText();
        inputSearch.setText("");
        action = "Tambah";
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, 
                "Apakah yakin ingin menghapus data ? ", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        
        if (getAnswer == JOptionPane.YES_OPTION) {
            try {
                computerControl.deleteDataComputer(idInput.getText());
                clearText();
                showComputer();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            } catch (Exception e) {
                System.out.println("Error : "+e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Data tidak jadi dihapus!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        setEditDeleteBtn(true);
        setComponent(false);
        
        try {
            Computer computer = computerControl.searchComputer(inputSearch.getText());
            
            if (computer  == null) {
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan",
                        "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                idInput.setText(computer.getId());
                namaInput.setText(computer.getNama());
                processorInput.setText(computer.getJenis());
                kapasitasRAMInput.setText(Integer.toString(computer.getKapasitasRAM()));
                if (computer.getJenis().equalsIgnoreCase("Desktop")) {
                    jRadioDesktop.setSelected(true);
                    dayaListrikInput.setText(Integer.toString(computer.getDayaListrik()));
                }else{
                    jRadioLaptop.setSelected(true);
                    bateraiInput.setText(Integer.toString(computer.getKapasitasBaterai()));
                }
            }
        } catch (Exception e) {
            System.out.println("Error : "+e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin Menambah/Ubah data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        switch (getAnswer) {
            case 0: //jika jawaban user adalah Yes
                try {
                inputKosongException();
                inputIDException();
                inputJenisException();

                String jenis = "";
                Computer c = null;


                if (jRadioLaptop.isSelected() == true) {
                    jenis = "Laptop";

                    c = new Computer(idInput.getText(), namaInput.getText(),
                       processorInput.getText(), jenis,
                       Integer.parseInt(kapasitasRAMInput.getText()), 
                       0,Integer.parseInt(bateraiInput.getText()));
                }else if (jRadioDesktop.isSelected() == true) {
                    jenis = "Desktop";

                    c = new Computer(idInput.getText(), namaInput.getText(),
                        processorInput.getText(),jenis ,
                       Integer.parseInt(kapasitasRAMInput.getText()), 
                       Integer.parseInt(dayaListrikInput.getText()),0);
                }


                if (action.equals("Tambah")) {
                    computerControl.insertDataComputer(c);
                    JOptionPane.showMessageDialog(null, "Data berhasil ditambah!");
                }else{
                    computerControl.updateDataComputer(c, idInput.getText());
                     JOptionPane.showMessageDialog(null, "Data berhasil diubah!");

                }
                clearText();
                showComputer();
                setComponent(false);
                setEditDeleteBtn(false);



            } catch (InputKosongException e) {
                JOptionPane.showMessageDialog(this, e.message());
            } catch ( NumberFormatException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            } catch ( InputIDException e){
                JOptionPane.showMessageDialog(this, e.message());
            } catch ( InputJenisException e){
                JOptionPane.showMessageDialog(this, e.message());
            } 
            break;
            case 1: 
                JOptionPane.showMessageDialog(null, "Data tidak jadi ditambah/ubah!");
            break;
        }
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void jRadioDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDesktopActionPerformed
        // TODO add your handling code here:
        bateraiInput.setEnabled(false);
        dayaListrikInput.setEnabled(true);
        bateraiInput.setText("");
        idInput.setText("DES-" + computerControl.countDataComputer());
        
        
    }//GEN-LAST:event_jRadioDesktopActionPerformed

    private void jRadioLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLaptopActionPerformed
        // TODO add your handling code here:
        bateraiInput.setEnabled(true);
        dayaListrikInput.setEnabled(false);
        dayaListrikInput.setText("");
        idInput.setText("LAP-" + computerControl.countDataLaptop());
        
        
    }//GEN-LAST:event_jRadioLaptopActionPerformed

    private void menuTransaksiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTransaksiBtnActionPerformed
        // TODO add your handling code here:
        TransaksiView tv = new TransaksiView();
        this.dispose();
        tv.setVisible(true);
    }//GEN-LAST:event_menuTransaksiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField bateraiInput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel containerInputDaya;
    private javax.swing.JPanel containerInputID;
    private javax.swing.JPanel containerInputJenis;
    private javax.swing.JPanel containerInputKapasitasBaterai;
    private javax.swing.JPanel containerInputKapasitasRAM;
    private javax.swing.JPanel containerInputNama;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JTextField dayaListrikInput;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioDesktop;
    private javax.swing.JRadioButton jRadioLaptop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JTextField kapasitasRAMInput;
    private javax.swing.JLabel kapasitasRAMLabel;
    private javax.swing.JPanel lecturerPanel;
    private javax.swing.JButton menuTransaksiBtn;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel nidLabel1;
    private javax.swing.JLabel nidLabel2;
    private javax.swing.JTextField processorInput;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel showDataPanelMovie;
    private javax.swing.JPanel showDataPanelSeri;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel titleContent;
    private javax.swing.JTextArea txtDesktop;
    private javax.swing.JTextArea txtLaptop;
    // End of variables declaration//GEN-END:variables
}
