/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ComputerControl;
import exception.InputKosongException;
import javax.swing.JOptionPane;
import control.ComputerControl;
import control.PembeliControl;
import control.TransaksiControl;
import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.TableModel;
import model.Computer;
import model.Pembeli;
import model.Transaksi;
import table.TableTransaksi;


/**
 *
 * @author LENOVO
 */
public class TransaksiView extends javax.swing.JFrame {
    private ComputerControl computerControl;
    private PembeliControl pembeliControl;
    private TransaksiControl transaksiControl;
    String action = null;
    List<Computer> listComputer;
    List<Pembeli> listPembeli;
    int selectedId = 0;
    
    
    

    /**
     * Creates new form TransaksiView
     */
    public TransaksiView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        
        
        computerControl = new ComputerControl();
        pembeliControl = new PembeliControl();
        transaksiControl = new TransaksiControl();
        
        showTransaksi();
        setPembeliToDropDown();
        setComputerToDropDown();
        setExtendedState(MAXIMIZED_BOTH);
        
        
    }
    
    public void setComponent(boolean value){
         computerDropDown.setEnabled(value);
         pembeliDropDown.setEnabled(value);
         tglTransaksiInput.setEnabled(value);
         totalHargaInput.setEnabled(value);
         mouseCheckBox.setEnabled(value);
         tasCheckBox.setEnabled(value);
         mousepadCheckBox.setEnabled(value);
         
         saveBtn1.setEnabled(value);
         cancelBtn.setEnabled(value);
         
    }
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        tglTransaksiInput.setText("");
        totalHargaInput.setText("");
        computerDropDown.setSelectedItem(ABORT);
        pembeliDropDown.setSelectedItem(ABORT);
        mouseCheckBox.setSelected(false);
        tasCheckBox.setSelected(false);
        mousepadCheckBox.setSelected(false);
        
        inputSearch.setText("");
    }
    
    public void setComputerToDropDown(){
        listComputer = computerControl.showListAllComputer();
        
        for (int i = 0; i < listComputer.size(); i++) {
           computerDropDown.addItem(listComputer.get(i));
        }
    }
    
    public void setPembeliToDropDown(){
        listPembeli = pembeliControl.showPembeli();
        
        for (int i = 0; i < listPembeli.size(); i++) {
            pembeliDropDown.addItem(listPembeli.get(i));
        }
    }
    
    public void showTransaksi(){
        tableTransaksi.setModel(transaksiControl.showTransaksi(""));
    }
    
    public void inputKosongException() throws InputKosongException{
        if (computerDropDown.getSelectedIndex() == -1 || pembeliDropDown.getSelectedIndex() == -1
                || tglTransaksiInput.getText().isEmpty() ||
                totalHargaInput.getText().isEmpty()) {
            throw new InputKosongException();
        }
        
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        computerPanel = new javax.swing.JPanel();
        computerIcon = new javax.swing.JLabel();
        transaksiPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pembeliPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        identitasPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        containerPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        saveBtn1 = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        inputSearch = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        formPanel = new javax.swing.JPanel();
        computerDropDown = new javax.swing.JComboBox<>();
        namaKomputerLabel = new javax.swing.JLabel();
        pembeliDropDown = new javax.swing.JComboBox<>();
        namaPembeliLabel = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        tanggalTransaksiLabel = new javax.swing.JLabel();
        tglTransaksiInput = new javax.swing.JTextField();
        totalHargaInput = new javax.swing.JTextField();
        mouseCheckBox = new javax.swing.JCheckBox();
        bonusPembelianLabel = new javax.swing.JLabel();
        tasCheckBox = new javax.swing.JCheckBox();
        mousepadCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBackground(new java.awt.Color(255, 51, 102));

        computerPanel.setBackground(new java.awt.Color(255, 153, 153));
        computerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                computerPanelMouseClicked(evt);
            }
        });

        computerIcon.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        computerIcon.setForeground(new java.awt.Color(0, 0, 0));
        computerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets.icons/computer.png"))); // NOI18N
        computerIcon.setText("Computer");
        computerIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        computerIcon.setMaximumSize(new java.awt.Dimension(1000, 1000));

        javax.swing.GroupLayout computerPanelLayout = new javax.swing.GroupLayout(computerPanel);
        computerPanel.setLayout(computerPanelLayout);
        computerPanelLayout.setHorizontalGroup(
            computerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computerPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(computerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        computerPanelLayout.setVerticalGroup(
            computerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, computerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(computerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        transaksiPanel.setBackground(new java.awt.Color(255, 153, 153));
        transaksiPanel.setForeground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets.icons/transaksi.png"))); // NOI18N
        jLabel1.setText("Transaksi");

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transaksiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pembeliPanel.setBackground(new java.awt.Color(255, 153, 153));
        pembeliPanel.setMinimumSize(new java.awt.Dimension(179, 65));
        pembeliPanel.setPreferredSize(new java.awt.Dimension(180, 65));
        pembeliPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembeliPanelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets.icons/pembeli.png"))); // NOI18N
        jLabel4.setText("Pembeli");

        javax.swing.GroupLayout pembeliPanelLayout = new javax.swing.GroupLayout(pembeliPanel);
        pembeliPanel.setLayout(pembeliPanelLayout);
        pembeliPanelLayout.setHorizontalGroup(
            pembeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembeliPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        pembeliPanelLayout.setVerticalGroup(
            pembeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pembeliPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        logoPanel.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets.icons/omah1.png"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("TRANSAKSI");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(computerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pembeliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(262, 262, 262))))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(computerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pembeliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        identitasPanel.setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Benidiktus Valerino Gozen - 200710606 - PBO B");

        javax.swing.GroupLayout identitasPanelLayout = new javax.swing.GroupLayout(identitasPanel);
        identitasPanel.setLayout(identitasPanelLayout);
        identitasPanelLayout.setHorizontalGroup(
            identitasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identitasPanelLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(241, 241, 241))
        );
        identitasPanelLayout.setVerticalGroup(
            identitasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, identitasPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        controlPanel.setBackground(new java.awt.Color(255, 204, 204));
        controlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        addBtn.setBackground(new java.awt.Color(51, 204, 0));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 0));
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(102, 102, 255));
        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        editBtn.setForeground(new java.awt.Color(0, 0, 0));
        editBtn.setText("Ubah");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 102));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(51, 51, 51));
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBtn1.setText("Save");
        saveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)))
                .addGap(26, 26, 26))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(saveBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn)
                .addGap(18, 18, 18))
        );

        searchPanel.setBackground(new java.awt.Color(255, 204, 204));
        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        searchBtn.setText("Cari");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputSearch)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addGap(29, 29, 29))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formPanel.setBackground(new java.awt.Color(255, 204, 204));
        formPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        namaKomputerLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        namaKomputerLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaKomputerLabel.setText("Nama Komputer");

        namaPembeliLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        namaPembeliLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaPembeliLabel.setText("Nama Pembeli");

        totalHargaLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        totalHargaLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalHargaLabel.setText("Total Harga");

        tanggalTransaksiLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        tanggalTransaksiLabel.setForeground(new java.awt.Color(0, 0, 0));
        tanggalTransaksiLabel.setText("Tanggal Transaksi");

        mouseCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        mouseCheckBox.setText("Mouse");
        mouseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseCheckBoxActionPerformed(evt);
            }
        });

        bonusPembelianLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        bonusPembelianLabel.setForeground(new java.awt.Color(0, 0, 0));
        bonusPembelianLabel.setText("Bonus Pembelian");

        tasCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        tasCheckBox.setText("Tas");

        mousepadCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        mousepadCheckBox.setText("Mousepad");

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(computerDropDown, 0, 278, Short.MAX_VALUE)
                    .addComponent(namaKomputerLabel)
                    .addComponent(namaPembeliLabel)
                    .addComponent(pembeliDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalHargaLabel)
                    .addComponent(tanggalTransaksiLabel)
                    .addComponent(tglTransaksiInput)
                    .addComponent(totalHargaInput))
                .addGap(49, 49, 49)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mouseCheckBox)
                    .addComponent(bonusPembelianLabel)
                    .addComponent(tasCheckBox)
                    .addComponent(mousepadCheckBox))
                .addGap(232, 232, 232))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKomputerLabel)
                    .addComponent(bonusPembelianLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computerDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mouseCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPembeliLabel)
                    .addComponent(tasCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembeliDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mousepadCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tanggalTransaksiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglTransaksiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalHargaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalHargaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(containerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(identitasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(identitasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        clearText();
        inputSearch.setText("");
        action = "Tambah";
        computerDropDown.setSelectedIndex(0);
        pembeliDropDown.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        setComponent(true);
        action = "Ubah";
        
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        switch (getAnswer) {
            case 0:
            try {
                transaksiControl.deleteTransaksi(selectedId);
                clearText();
                showTransaksi();
                setComponent(false);
                setEditDeleteBtn(false);
                
                
            } catch (Exception e) {
                System.out.println("Error : " + e.getMessage());
            }
                break;
             case 1:
                break;
            default:
                throw new AssertionError();
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        setEditDeleteBtn(false);
        setComponent(false);
        
        try {
            TableTransaksi transaksi = transaksiControl.showTransaksi(inputSearch.getText());
            
            if (transaksi.getRowCount() == 0) {
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan","Konfirmasi",JOptionPane.DEFAULT_OPTION);
                
                
            }else{
                tableTransaksi.setModel(transaksi);
                
            }
            
            clearText();
        } catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        // TODO add your handling code here:
        int indexComputer = -1;
        int indexPembeli = -1;
        setEditDeleteBtn(true);
        setComponent(false);
        
        
        
        int clickedRow = tableTransaksi.getSelectedRow();
        
        TableModel tableModel = tableTransaksi.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString());
        tglTransaksiInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        totalHargaInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        
        
        String bonusPembelian = tableModel.getValueAt(clickedRow, 5).toString();
        switch (bonusPembelian) {
            case "Mouse,-,-":
                mouseCheckBox.setSelected(true);
                tasCheckBox.setSelected(false);
                mousepadCheckBox.setSelected(false);
                break;
             case "Mouse,Tas,-":
                mouseCheckBox.setSelected(true);
                tasCheckBox.setSelected(true);
                mousepadCheckBox.setSelected(false);
                break;
             case "Mouse,Tas,Mousepad":
                mouseCheckBox.setSelected(true);
                tasCheckBox.setSelected(true);
                mousepadCheckBox.setSelected(true);
                break;
             case "-,Tas,Mousepad":
                mouseCheckBox.setSelected(false);
                tasCheckBox.setSelected(true);
                mousepadCheckBox.setSelected(true);
                break;
             case "-,Tas,-":
                mouseCheckBox.setSelected(false);
                tasCheckBox.setSelected(true);
                mousepadCheckBox.setSelected(false);
                break;
             case "Mouse,-,Mousepad":
                mouseCheckBox.setSelected(true);
                tasCheckBox.setSelected(false);
                mousepadCheckBox.setSelected(true);
                break;
             case "-,-,Mouse":
                mouseCheckBox.setSelected(false);
                tasCheckBox.setSelected(false);
                mousepadCheckBox.setSelected(true);
                break;
             case "-,-,-":
                mouseCheckBox.setSelected(false);
                tasCheckBox.setSelected(false);
                mousepadCheckBox.setSelected(false);
                break;
            case "-,-,Mousepad":
                mouseCheckBox.setSelected(false);
                tasCheckBox.setSelected(false);
                mousepadCheckBox.setSelected(true);
                break;
           
          
               
            default:
                throw new AssertionError();
        }
        
        String idComputer = tableModel.getValueAt(clickedRow, 10).toString();
        
       
        
        for (Computer computer : listComputer) {
            
            if (computer.getId().equals(idComputer) ) {
                indexComputer = listComputer.indexOf(computer);
            }
        }
        
        computerDropDown.setSelectedIndex(indexComputer);
       
        int idPembeli = Integer.parseInt(tableModel.getValueAt(clickedRow, 9).toString());
        
        for (Pembeli pembeli : listPembeli) {
            if (pembeli.getId() == idPembeli ) {
                indexPembeli = listPembeli.indexOf(pembeli);
            }
        }
        
        pembeliDropDown.setSelectedIndex(indexPembeli);
    }                                            

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void mouseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseCheckBoxActionPerformed

    private void saveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtn1ActionPerformed
        // TODO add your handling code here:
        try {
            inputKosongException();
            String bonusPembelian = "";
            
            int selectedIndex = computerDropDown.getSelectedIndex();
            Computer selectedComputer = listComputer.get(selectedIndex);
            
            selectedIndex = pembeliDropDown.getSelectedIndex();
            Pembeli selectedPembeli = listPembeli.get(selectedIndex);
            
            
            if (mouseCheckBox.isSelected() && !tasCheckBox.isSelected() && !mousepadCheckBox.isSelected()  ) {
                bonusPembelian = "Mouse,-,-";
            }else if (mouseCheckBox.isSelected() && tasCheckBox.isSelected() && !mousepadCheckBox.isSelected()) {
                bonusPembelian = "Mouse,Tas,-";
            }else if (mouseCheckBox.isSelected() && tasCheckBox.isSelected() && mousepadCheckBox.isSelected()) {
                bonusPembelian = "Mouse,Tas,Mousepad";
            }else if (!mouseCheckBox.isSelected() && tasCheckBox.isSelected() && !mousepadCheckBox.isSelected()) {
                bonusPembelian = "-,Tas,-";
            }else if (mouseCheckBox.isSelected() && tasCheckBox.isSelected() &&! mousepadCheckBox.isSelected()) {
                bonusPembelian = "Mouse,Tas,-";
            }else if (mouseCheckBox.isSelected() && !tasCheckBox.isSelected() && mousepadCheckBox.isSelected()) {
                bonusPembelian = "Mouse,-,Mousepad";
            }else if (!mouseCheckBox.isSelected() && tasCheckBox.isSelected() && mousepadCheckBox.isSelected()) {
                bonusPembelian = "-,Tas,Mousepad";
            }else{
                bonusPembelian = "-,-,-";
            }
            
            if (action.equals("Tambah")) {
                Transaksi tr = new Transaksi(tglTransaksiInput.getText(), 
                        totalHargaInput.getText(), 
                        bonusPembelian, 
                        selectedComputer, 
                        selectedPembeli);
                
                
                transaksiControl.insertTransaksi(tr);
            }else{
                Transaksi tr = new Transaksi(selectedId,
                        tglTransaksiInput.getText(), 
                        totalHargaInput.getText(), 
                        bonusPembelian, 
                        selectedComputer, 
                        selectedPembeli);
                
                
                transaksiControl.updateTransaksi(tr);
            }
            clearText();
            showTransaksi();
            setComponent(false);
            
            
            
            setEditDeleteBtn(false);
            
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_saveBtn1ActionPerformed

    private void computerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_computerPanelMouseClicked
        // TODO add your handling code here:
        ComputerView cv = new ComputerView();
        this.dispose();
        cv.setVisible(true);
        
    }//GEN-LAST:event_computerPanelMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void pembeliPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembeliPanelMouseClicked
        // TODO add your handling code here:
        PembeliView pv = new PembeliView();
        this.dispose();
        pv.setVisible(true);
    }//GEN-LAST:event_pembeliPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel bonusPembelianLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<Computer> computerDropDown;
    private javax.swing.JLabel computerIcon;
    private javax.swing.JPanel computerPanel;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel identitasPanel;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JCheckBox mouseCheckBox;
    private javax.swing.JCheckBox mousepadCheckBox;
    private javax.swing.JLabel namaKomputerLabel;
    private javax.swing.JLabel namaPembeliLabel;
    private javax.swing.JComboBox<Pembeli> pembeliDropDown;
    private javax.swing.JPanel pembeliPanel;
    private javax.swing.JButton saveBtn1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JLabel tanggalTransaksiLabel;
    private javax.swing.JCheckBox tasCheckBox;
    private javax.swing.JTextField tglTransaksiInput;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField totalHargaInput;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
